//! Agent turn: load session history, call the configured provider (Ollama, LM Studio, vLLM, NIM), append reply.
//! Supports optional tools: when the model returns tool_calls, we execute them and re-call the model until done.
//!
//! For orchestration, see [`run_turn_with_messages`] — in-memory turns without session persistence (worker / delegation).
//! Gateway dispatch uses [`run_turn_dyn`] with [`crate::orchestration::ProviderClients::as_dyn`].
//! When the gateway passes [`crate::orchestration::DelegateContext`], the built-in tool **`delegate_task`** runs a worker
//! via [`crate::orchestration::execute_delegate_task`] on another enabled provider: per-worker system context and tools
//! when **`workerId`** is set, otherwise the orchestrator’s skill bundle; nested **`delegate_task`** is disabled (see epic).

use crate::orchestration::{
    execute_delegate_task, DelegateContext, DelegateObservability, DELEGATE_TASK_TOOL_NAME,
};
use crate::providers::{ChatMessage, Provider, ProviderError, ToolCall, ToolDefinition};
use crate::session::SessionStore;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

/// Result of one agent turn: final text content and any tool/function calls that were executed during the turn.
#[derive(Debug, Clone)]
pub struct AgentTurnResult {
    pub content: String,
    pub tool_calls: Vec<ToolCall>,
    /// Tool/function call outputs (as strings) executed during the turn.
    ///
    /// This is parallel to [`AgentTurnResult::tool_calls`] by index: `tool_results[i]` is the output
    /// for `tool_calls[i]`.
    pub tool_results: Vec<String>,
    /// Whether any model response during this turn was truncated (`finish_reason: "length"`).
    pub truncated: bool,
    /// Whether the agent loop hit its iteration limit while the model was still generating
    /// tool calls. When this is true, some planned work was not executed.
    pub loop_limit_reached: bool,
    /// Tool calls that were generated by the model but not executed because the loop
    /// iteration limit was reached. Empty when `loop_limit_reached` is false.
    /// The accompanying `content` (assistant text) for these calls is stored in the
    /// top-level `content` field.
    pub pending_tool_calls: Vec<ToolCall>,
    /// Whether the turn was stopped by a stop signal between iterations. When true,
    /// the agent finished the current tool call or model request, then paused before
    /// the next iteration. The session transcript remains valid and the user can
    /// send a new message to continue.
    pub stopped: bool,
}

/// Executes a tool by name and JSON arguments. Returns output or error string.
pub trait ToolExecutor: Send + Sync {
    fn execute(&self, name: &str, args: &serde_json::Value, session_id: Option<&str>) -> Result<String, String>;
}

/// Run one agent turn: load session messages, call the given provider (streaming when on_chunk is Some); if tools are provided and the model returns tool_calls, execute them and re-call until no more tool_calls or max iterations.
/// `model` is the provider-specific model name (no prefix; e.g. `llama3.2:3b` for Ollama, `llama-3.2-3B-instruct` for LM Studio).
pub async fn run_turn<B: Provider>(
    store: &SessionStore,
    session_id: &str,
    provider: &B,
    model: &str,
    system_context: Option<&str>,
    max_session_messages: Option<usize>,
    max_tool_loop_iterations: u32,
    tools: Option<Vec<ToolDefinition>>,
    tool_executor: Option<&dyn ToolExecutor>,
    delegate: Option<DelegateContext<'_>>,
    on_chunk: Option<&mut (dyn FnMut(&str) + Send)>,
    stop_flag: Option<Arc<AtomicBool>>,
) -> Result<AgentTurnResult, ProviderError> {
    run_turn_dyn(
        store,
        session_id,
        provider as &dyn Provider,
        model,
        system_context,
        max_session_messages,
        max_tool_loop_iterations,
        tools,
        tool_executor,
        delegate,
        on_chunk,
        stop_flag,
    )
    .await
}

/// Same as [`run_turn`] but accepts a [`Provider`] trait object (e.g. from [`crate::orchestration::ProviderClients::as_dyn`]).
pub async fn run_turn_dyn(
    store: &SessionStore,
    session_id: &str,
    provider: &dyn Provider,
    model: &str,
    system_context: Option<&str>,
    max_session_messages: Option<usize>,
    max_tool_loop_iterations: u32,
    tools: Option<Vec<ToolDefinition>>,
    tool_executor: Option<&dyn ToolExecutor>,
    delegate: Option<DelegateContext<'_>>,
    mut on_chunk: Option<&mut (dyn FnMut(&str) + Send)>,
    stop_flag: Option<Arc<AtomicBool>>,
) -> Result<AgentTurnResult, ProviderError> {
    let session = store
        .get(session_id)
        .await
        .ok_or_else(|| ProviderError::Session("session not found".to_string()))?;

    let mut messages: Vec<ChatMessage> = session
        .messages
        .iter()
        .map(|m| ChatMessage {
            role: m.role.clone(),
            content: m.content.clone(),
            tool_calls: m.tool_calls.clone(),
            tool_name: m.tool_name.clone(),
        })
        .collect();

    if let Some(limit) = max_session_messages {
        if limit > 0 && messages.len() > limit {
            let start = messages.len() - limit;
            messages = messages[start..].to_vec();
        }
    }

    if let Some(ctx) = system_context {
        if !ctx.trim().is_empty() {
            messages.insert(
                0,
                ChatMessage {
                    role: "system".to_string(),
                    content: ctx.to_string(),
                    tool_calls: None,
                    tool_name: None,
                },
            );
        }
    }

    execute_turn_main(
        provider,
        model,
        &mut messages,
        tools,
        tool_executor,
        &mut on_chunk,
        Some((store, session_id)),
        delegate,
        max_tool_loop_iterations,
        stop_flag,
    )
    .await
}

/// Run a single turn with an explicit message list. **Does not** read or write [`SessionStore`].
///
/// Use this for **worker** or **delegated** subtasks: build `messages` (e.g. system + user instruction), pick a
/// [`Provider`] and model id, then consume [`AgentTurnResult`]. The same tool loop as [`run_turn`] applies
/// (`max_tool_loop_iterations` iterations); nothing is persisted — the orchestrator merges results into the main session.
///
/// Streaming is not supported here (`on_chunk` is unused); add later if needed.
pub async fn run_turn_with_messages<B: Provider>(
    provider: &B,
    model: &str,
    messages: Vec<ChatMessage>,
    tools: Option<Vec<ToolDefinition>>,
    tool_executor: Option<&dyn ToolExecutor>,
    max_tool_loop_iterations: u32,
) -> Result<AgentTurnResult, ProviderError> {
    run_turn_with_messages_dyn(
        provider as &dyn Provider,
        model,
        messages,
        tools,
        tool_executor,
        max_tool_loop_iterations,
        None,
    )
    .await
}

/// Same as [`run_turn_with_messages`] but accepts a [`Provider`] trait object.
pub async fn run_turn_with_messages_dyn(
    provider: &dyn Provider,
    model: &str,
    mut messages: Vec<ChatMessage>,
    tools: Option<Vec<ToolDefinition>>,
    tool_executor: Option<&dyn ToolExecutor>,
    max_tool_loop_iterations: u32,
    observability: Option<&DelegateObservability>,
) -> Result<AgentTurnResult, ProviderError> {
    let mut on_chunk: Option<&mut (dyn FnMut(&str) + Send)> = None;
    execute_turn_worker(
        provider,
        model,
        &mut messages,
        tools,
        tool_executor,
        &mut on_chunk,
        None,
        max_tool_loop_iterations,
        observability,
    )
    .await
}

/// In-memory tool loop without `delegate_task` handling (nested delegation). Used by [`run_turn_with_messages_dyn`].
async fn execute_turn_worker(
    provider: &dyn Provider,
    model: &str,
    messages: &mut Vec<ChatMessage>,
    tools: Option<Vec<ToolDefinition>>,
    tool_executor: Option<&dyn ToolExecutor>,
    on_chunk: &mut Option<&mut (dyn FnMut(&str) + Send)>,
    persist: Option<(&SessionStore, &str)>,
    max_tool_loop_iterations: u32,
    observability: Option<&DelegateObservability>,
) -> Result<AgentTurnResult, ProviderError> {
    let model_name = model.trim();
    let model_name = if model_name.is_empty() {
        log::warn!("agent: configured model was empty, using fallback");
        crate::orchestration::DEFAULT_MODEL_FALLBACK
    } else {
        model_name
    };
    log::info!("agent: using model {}", model_name);
    let tools_ref = tools.as_ref();
    let mut loop_count = 0;
    let mut executed_tool_calls: Vec<ToolCall> = Vec::new();
    let mut executed_tool_results: Vec<String> = Vec::new();
    let mut last_content: String;
    let mut last_tool_calls: Vec<ToolCall>;
    let mut truncated = false;
    let mut loop_limit_reached = false;
    let mut pending_tool_calls: Vec<ToolCall> = Vec::new();

    loop {
        let use_stream = on_chunk.is_some() && loop_count == 0;
        let res = if use_stream {
            let cb = on_chunk.as_mut().unwrap();
            let mut delta_cb = |s: &str| cb(s);
            provider
                .chat_stream(
                    model_name,
                    messages.clone(),
                    tools_ref.cloned(),
                    &mut delta_cb,
                )
                .await?
        } else {
            provider
                .chat(model_name, messages.clone(), false, tools_ref.cloned())
                .await?
        };
        last_content = res.content().to_string();
        last_tool_calls = res.tool_calls().to_vec();

        let was_truncated = res.is_truncated();
        if was_truncated {
            truncated = true;
            log::warn!(
                "agent: model response was truncated (finish_reason: {}), some tool calls may have been omitted",
                res.finish_reason.as_ref().map(|r| r.to_string()).unwrap_or_else(|| "unknown".to_string())
            );
        }

        // Diagnostic logging: record usage info for investigating phantom edits.
        // When a phantom edit occurs, this data helps determine whether the provider's
        // output was constrained by context (large prompt_tokens, small completion_tokens).
        log::info!(
            "agent: loop iteration {} — finish_reason={}, tool_calls={}, content_len={}{}",
            loop_count,
            res.finish_reason.as_ref().map(|r| r.to_string()).unwrap_or_else(|| "none".to_string()),
            last_tool_calls.len(),
            last_content.len(),
            res.usage.as_ref().map(|u| format!(", usage=({})", u)).unwrap_or_else(String::new),
        );

        // Emit intermediate assistant message content so the user can see the
        // model's output between tool calls. Without this, only the final
        // iteration's content is visible — all intermediate messages are lost.
        if !last_tool_calls.is_empty() && !last_content.trim().is_empty() {
            if let Some(ref obs) = observability {
                obs.emit_assistant_message(&last_content, loop_count);
            }
        }

        let assistant_msg = ChatMessage {
            role: "assistant".to_string(),
            content: last_content.clone(),
            tool_calls: if last_tool_calls.is_empty() {
                None
            } else {
                Some(last_tool_calls.clone())
            },
            tool_name: None,
        };

        if let Some((store, session_id)) = persist {
            store
                .append_message_full(
                    session_id,
                    "assistant",
                    &assistant_msg.content,
                    assistant_msg.tool_calls.clone(),
                    None,
                )
                .await
                .map_err(|e| ProviderError::Session(e.to_string()))?;
        }

        if last_tool_calls.is_empty() {
            // No tool calls — if truncated, inject a notice so the model can retry.
            if was_truncated {
                let notice = "⚠️ Your previous response was truncated (finish_reason: length). \
                    Some tool calls may have been omitted. Please re-emit any missing tool calls.";
                let notice_msg = ChatMessage {
                    role: "user".to_string(),
                    content: notice.to_string(),
                    tool_calls: None,
                    tool_name: None,
                };
                if let Some((store, session_id)) = persist {
                    store
                        .append_message_full(session_id, "user", notice, None, None)
                        .await
                        .map_err(|e| ProviderError::Session(e.to_string()))?;
                }
                messages.push(assistant_msg);
                messages.push(notice_msg);
                loop_count += 1;
                if loop_count >= (max_tool_loop_iterations as i32).try_into().unwrap() {
                    log::warn!("agent: max tool loop iterations reached after truncation");
                    loop_limit_reached = true;
                    if !last_tool_calls.is_empty() {
                        pending_tool_calls = last_tool_calls.clone();
                    }
                    break;
                }
                continue;
            }
            break;
        }

        loop_count += 1;
        if loop_count >= (max_tool_loop_iterations as i32).try_into().unwrap() {
            log::warn!("agent: max tool loop iterations reached ({}), some tool calls were not executed", loop_count);
            loop_limit_reached = true;
            pending_tool_calls = last_tool_calls.clone();
            break;
        }

        let needs_executor = last_tool_calls
            .iter()
            .any(|c| c.function.name != DELEGATE_TASK_TOOL_NAME);
        if needs_executor && tool_executor.is_none() {
            log::debug!("agent: tool_calls returned but no executor");
            break;
        }

        messages.push(assistant_msg);
        for (idx, call) in last_tool_calls.iter().enumerate() {
            let name = call.function.name.as_str();
            let args = &call.function.arguments;

            // Emit session.tool_call event before execution so the desktop can
            // render worker tool calls as separate timeline entries as they happen.
            if let Some(ref obs) = observability {
                obs.emit_tool_call(name, args, executed_tool_calls.len() + idx);
            }

            let result = if name == DELEGATE_TASK_TOOL_NAME {
                log::debug!("agent: delegate_task not available in worker turn");
                "error: delegate_task is not available in this context".to_string()
            } else {
                match tool_executor {
                    Some(executor) => match executor.execute(name, args, persist.map(|(_, sid)| sid)) {
                        Ok(out) => out.clone(),
                        Err(e) => {
                            // Log the short status at warn level; log the
                            // full detail (expected/actual diffs, etc.) at
                            // debug level so it doesn't overwhelm the chat
                            // log view.
                            let (base, detail) = e.split_once(": ").unwrap_or((&e, ""));
                            log::warn!("agent: tool {} failed: {}", name, base);
                            if !detail.is_empty() {
                                log::debug!("agent: tool {} failed: {}: {}", name, base, detail);
                            }
                            format!("error: {}", e)
                        }
                    },
                    None => {
                        log::debug!("agent: missing executor for tool");
                        format!("error: no executor for tool {}", name)
                    }
                }
            };
            executed_tool_results.push(result.clone());

            // Emit session.tool_result event after execution completes.
            if let Some(ref obs) = observability {
                obs.emit_tool_result(name, &result, executed_tool_calls.len() + idx);
            }

            messages.push(ChatMessage {
                role: "tool".to_string(),
                content: result.clone(),
                tool_calls: None,
                tool_name: Some(name.to_string()),
            });
            if let Some((store, session_id)) = persist {
                store
                    .append_message_full(session_id, "tool", &result, None, Some(name.to_string()))
                    .await
                    .map_err(|e| ProviderError::Session(e.to_string()))?;
            }
        }

        executed_tool_calls.extend(last_tool_calls.clone());

        // If the response was truncated, inject a notice so the model can re-emit
        // any tool calls that were cut off. The tool calls that were present have
        // already been executed above.
        if was_truncated {
            let notice = "⚠️ Your previous response was truncated (finish_reason: length). \
                Some tool calls may have been omitted. Please verify your last tool call and \
                re-emit any missing tool calls.";
            let notice_msg = ChatMessage {
                role: "user".to_string(),
                content: notice.to_string(),
                tool_calls: None,
                tool_name: None,
            };
            if let Some((store, session_id)) = persist {
                store
                    .append_message_full(session_id, "user", notice, None, None)
                    .await
                    .map_err(|e| ProviderError::Session(e.to_string()))?;
            }
            messages.push(notice_msg);
            if loop_count >= (max_tool_loop_iterations as i32).try_into().unwrap() {
                log::warn!("agent: max tool loop iterations reached after truncation");
                loop_limit_reached = true;
                if !last_tool_calls.is_empty() {
                    pending_tool_calls = last_tool_calls.clone();
                }
                break;
            }
            continue;
        }
    }

    Ok(AgentTurnResult {
        content: last_content,
        tool_calls: executed_tool_calls,
        tool_results: executed_tool_results,
        truncated,
        loop_limit_reached,
        pending_tool_calls,
        stopped: false,
    })
}
/// Session-backed tool loop with `delegate_task` (nested worker turns use [`execute_turn_worker`] only).
async fn execute_turn_main(
    provider: &dyn Provider,
    model: &str,
    messages: &mut Vec<ChatMessage>,
    tools: Option<Vec<ToolDefinition>>,
    tool_executor: Option<&dyn ToolExecutor>,
    on_chunk: &mut Option<&mut (dyn FnMut(&str) + Send)>,
    persist: Option<(&SessionStore, &str)>,
    delegate: Option<DelegateContext<'_>>,
    max_tool_loop_iterations: u32,
    stop_flag: Option<Arc<AtomicBool>>,
) -> Result<AgentTurnResult, ProviderError> {
    let model_name = model.trim();
    let model_name = if model_name.is_empty() {
        log::warn!("agent: configured model was empty, using fallback");
        crate::orchestration::DEFAULT_MODEL_FALLBACK
    } else {
        model_name
    };
    log::info!("agent: using model {}", model_name);
    let tools_ref = tools.as_ref();
    let mut loop_count = 0;
    let mut executed_tool_calls: Vec<ToolCall> = Vec::new();
    let mut executed_tool_results: Vec<String> = Vec::new();
    let mut last_content = String::new();
    let mut last_tool_calls: Vec<ToolCall>;
    let mut truncated = false;
    let max_delegations_per_turn = delegate
        .as_ref()
        .and_then(|d| d.agents.max_delegations_per_turn);
    let mut delegate_calls_this_turn: usize = 0;
    let mut loop_limit_reached = false;
    let mut pending_tool_calls: Vec<ToolCall> = Vec::new();
    let mut stopped = false;

    // Clear any stale stop flag from a previous turn before starting.
    if let Some(ref flag) = stop_flag {
        flag.store(false, Ordering::SeqCst);
    }

    loop {
        // Check stop flag before each iteration. If set, break out of the loop
        // gracefully — the current tool call or model request has already completed.
        if let Some(ref flag) = stop_flag {
            if flag.load(Ordering::SeqCst) {
                log::info!("agent: stop signal received, pausing turn after iteration {}", loop_count);
                stopped = true;
                // Emit turn stopped event so connected clients know the turn was paused.
                if let Some(ref d) = delegate {
                    if let Some(ref obs) = d.observability {
                        obs.emit_turn_stopped();
                    }
                }
                break;
            }
        }

        let use_stream = on_chunk.is_some() && loop_count == 0;
        let res = if use_stream {
            let cb = on_chunk.as_mut().unwrap();
            let mut delta_cb = |s: &str| cb(s);
            provider
                .chat_stream(
                    model_name,
                    messages.clone(),
                    tools_ref.cloned(),
                    &mut delta_cb,
                )
                .await?
        } else {
            provider
                .chat(model_name, messages.clone(), false, tools_ref.cloned())
                .await?
        };
        last_content = res.content().to_string();
        last_tool_calls = res.tool_calls().to_vec();

        let was_truncated = res.is_truncated();
        if was_truncated {
            truncated = true;
            log::warn!(
                "agent: model response was truncated (finish_reason: {}), some tool calls may have been omitted",
                res.finish_reason.as_ref().map(|r| r.to_string()).unwrap_or_else(|| "unknown".to_string())
            );
        }

        // Diagnostic logging: record usage info for investigating phantom edits.
        // When a phantom edit occurs, this data helps determine whether the provider's
        // output was constrained by context (large prompt_tokens, small completion_tokens).
        log::info!(
            "agent: loop iteration {} — finish_reason={}, tool_calls={}, content_len={}{}",
            loop_count,
            res.finish_reason.as_ref().map(|r| r.to_string()).unwrap_or_else(|| "none".to_string()),
            last_tool_calls.len(),
            last_content.len(),
            res.usage.as_ref().map(|u| format!(", usage=({})", u)).unwrap_or_else(String::new),
        );

        // Emit intermediate assistant message content so the user can see the
        // model's output between tool calls. Without this, only the final
        // iteration's content is visible — all intermediate messages are lost.
        if !last_tool_calls.is_empty() && !last_content.trim().is_empty() {
            if let Some(ref d) = delegate {
                if let Some(ref obs) = d.observability {
                    obs.emit_assistant_message(&last_content, loop_count);
                }
            }
        }

        let assistant_msg = ChatMessage {
            role: "assistant".to_string(),
            content: last_content.clone(),
            tool_calls: if last_tool_calls.is_empty() {
                None
            } else {
                Some(last_tool_calls.clone())
            },
            tool_name: None,
        };

        if let Some((store, session_id)) = persist {
            store
                .append_message_full(
                    session_id,
                    "assistant",
                    &assistant_msg.content,
                    assistant_msg.tool_calls.clone(),
                    None,
                )
                .await
                .map_err(|e| ProviderError::Session(e.to_string()))?;
        }

        if last_tool_calls.is_empty() {
            // No tool calls — if truncated, inject a notice so the model can retry.
            if was_truncated {
                let notice = "⚠️ Your previous response was truncated (finish_reason: length). \
                    Some tool calls may have been omitted. Please re-emit any missing tool calls.";
                let notice_msg = ChatMessage {
                    role: "user".to_string(),
                    content: notice.to_string(),
                    tool_calls: None,
                    tool_name: None,
                };
                if let Some((store, session_id)) = persist {
                    store
                        .append_message_full(session_id, "user", notice, None, None)
                        .await
                        .map_err(|e| ProviderError::Session(e.to_string()))?;
                }
                messages.push(assistant_msg);
                messages.push(notice_msg);
                loop_count += 1;
                if loop_count >= (max_tool_loop_iterations as i32).try_into().unwrap() {
                    log::warn!("agent: max tool loop iterations reached after truncation");
                    loop_limit_reached = true;
                    if !last_tool_calls.is_empty() {
                        pending_tool_calls = last_tool_calls.clone();
                    }
                    break;
                }
                continue;
            }
            break;
        }

        loop_count += 1;
        if loop_count >= (max_tool_loop_iterations as i32).try_into().unwrap() {
            log::warn!("agent: max tool loop iterations reached ({}), some tool calls were not executed", loop_count);
            loop_limit_reached = true;
            pending_tool_calls = last_tool_calls.clone();
            break;
        }

        let needs_executor = last_tool_calls
            .iter()
            .any(|c| c.function.name != DELEGATE_TASK_TOOL_NAME);
        if needs_executor && tool_executor.is_none() {
            log::debug!("agent: tool_calls returned but no executor");
            break;
        }

        messages.push(assistant_msg);
        for (idx, call) in last_tool_calls.iter().enumerate() {
            let name = call.function.name.as_str();
            let args = &call.function.arguments;

            // Emit session.tool_call event before execution so the desktop can
            // render tool calls as separate timeline entries as they happen.
            if let Some(ref d) = delegate {
                if let Some(ref obs) = d.observability {
                    obs.emit_tool_call(name, args, executed_tool_calls.len() + idx);
                }
            }

            let result = if name == DELEGATE_TASK_TOOL_NAME {
                delegate_calls_this_turn += 1;
                if let Some(max) = max_delegations_per_turn {
                    if delegate_calls_this_turn > max {
                        log::warn!(
                            "agent: delegate_task rejected (max delegations per turn: {})",
                            max
                        );
                        if let Some(ref d) = delegate {
                            if let Some(ref obs) = d.observability {
                                obs.emit_rejected(args, "max_delegations_per_turn", Some(max));
                            }
                        }
                        format!(
                            "error: max delegations per turn exceeded (maxDelegationsPerTurn={})",
                            max
                        )
                    } else {
                        match delegate {
                            Some(ref ctx) => match execute_delegate_task(ctx, args).await {
                                Ok(s) => s,
                                Err(e) => {
                                    log::warn!("agent: delegate_task failed: {}", e);
                                    format!("error: {}", e)
                                }
                            },
                            None => {
                                log::debug!("agent: delegate_task not available");
                                "error: delegate_task is not available in this context".to_string()
                            }
                        }
                    }
                } else {
                    match delegate {
                        Some(ref ctx) => match execute_delegate_task(ctx, args).await {
                            Ok(s) => s,
                            Err(e) => {
                                log::warn!("agent: delegate_task failed: {}", e);
                                format!("error: {}", e)
                            }
                        },
                        None => {
                            log::debug!("agent: delegate_task not available");
                            "error: delegate_task is not available in this context".to_string()
                        }
                    }
                }
            } else {
                match tool_executor {
                    Some(executor) => match executor.execute(name, args, persist.map(|(_, sid)| sid)) {
                        Ok(out) => out.clone(),
                        Err(e) => {
                            // Log the short status at warn level; log the
                            // full detail (expected/actual diffs, etc.) at
                            // debug level so it doesn't overwhelm the chat
                            // log view.
                            let (base, detail) = e.split_once(": ").unwrap_or((&e, ""));
                            log::warn!("agent: tool {} failed: {}", name, base);
                            if !detail.is_empty() {
                                log::debug!("agent: tool {} failed: {}: {}", name, base, detail);
                            }
                            format!("error: {}", e)
                        }
                    },
                    None => {
                        log::debug!("agent: missing executor for tool");
                        format!("error: no executor for tool {}", name)
                    }
                }
            };
            executed_tool_results.push(result.clone());

            // Emit session.tool_result event after execution completes.
            if let Some(ref d) = delegate {
                if let Some(ref obs) = d.observability {
                    obs.emit_tool_result(name, &result, executed_tool_calls.len() + idx);
                }
            }

            messages.push(ChatMessage {
                role: "tool".to_string(),
                content: result.clone(),
                tool_calls: None,
                tool_name: Some(name.to_string()),
            });
            if let Some((store, session_id)) = persist {
                store
                    .append_message_full(session_id, "tool", &result, None, Some(name.to_string()))
                    .await
                    .map_err(|e| ProviderError::Session(e.to_string()))?;
            }

        }

        executed_tool_calls.extend(last_tool_calls.clone());

        // If the response was truncated, inject a notice so the model can re-emit
        // any tool calls that were cut off. The tool calls that were present have
        // already been executed above.
        if was_truncated {
            let notice = "⚠️ Your previous response was truncated (finish_reason: length). \
                Some tool calls may have been omitted. Please verify your last tool call and \
                re-emit any missing tool calls.";
            let notice_msg = ChatMessage {
                role: "user".to_string(),
                content: notice.to_string(),
                tool_calls: None,
                tool_name: None,
            };
            if let Some((store, session_id)) = persist {
                store
                    .append_message_full(session_id, "user", notice, None, None)
                    .await
                    .map_err(|e| ProviderError::Session(e.to_string()))?;
            }
            messages.push(notice_msg);
            if loop_count >= (max_tool_loop_iterations as i32).try_into().unwrap() {
                log::warn!("agent: max tool loop iterations reached after truncation");
                loop_limit_reached = true;
                if !last_tool_calls.is_empty() {
                    pending_tool_calls = last_tool_calls.clone();
                }
                break;
            }
            continue;
        }
    }
    // Emit tool loop limit event so connected clients can inform the user.
    if loop_limit_reached {
        if let Some(ref d) = delegate {
            if let Some(ref obs) = d.observability {
                obs.emit_tool_loop_limit(&pending_tool_calls);
            }
        }
    }
    Ok(AgentTurnResult {
        content: last_content,
        tool_calls: executed_tool_calls,
        tool_results: executed_tool_results,
        truncated,
        loop_limit_reached,
        pending_tool_calls,
        stopped,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::providers::{ChatResponse, FinishReason, ToolCallFunction};
    use async_trait::async_trait;
    use std::sync::{Arc, Mutex};

    /// Mock provider that returns a sequence of pre-programmed responses.
    /// Each call to `chat` pops the next response from the queue.
    #[derive(Clone)]
    struct MockProvider {
        responses: Arc<Mutex<Vec<ChatResponse>>>,
    }

    impl MockProvider {
        fn new(responses: Vec<ChatResponse>) -> Self {
            Self {
                responses: Arc::new(Mutex::new(responses)),
            }
        }
    }

    #[async_trait]
    impl Provider for MockProvider {
        async fn chat(
            &self,
            _model: &str,
            _messages: Vec<ChatMessage>,
            _stream: bool,
            _tools: Option<Vec<ToolDefinition>>,
        ) -> Result<ChatResponse, ProviderError> {
            let mut responses = self.responses.lock().unwrap();
            if responses.is_empty() {
                Ok(make_chat_response(
                    Some(ChatMessage {
                        role: "assistant".to_string(),
                        content: "no more responses".to_string(),
                        tool_calls: None,
                        tool_name: None,
                    }),
                    true,
                    None,
                ))
            } else {
                Ok(responses.remove(0))
            }
        }

        async fn chat_stream(
            &self,
            model: &str,
            messages: Vec<ChatMessage>,
            _tools: Option<Vec<ToolDefinition>>,
            _on_chunk: &mut (dyn for<'a> FnMut(&'a str) + Send),
        ) -> Result<ChatResponse, ProviderError> {
            self.chat(model, messages, false, None).await
        }
    }

    /// Simple tool executor that records calls and returns a canned result.
    #[derive(Clone)]
    struct MockToolExecutor {
        results: Arc<Mutex<Vec<String>>>,
    }

    impl MockToolExecutor {
        fn new() -> Self {
            Self {
                results: Arc::new(Mutex::new(Vec::new())),
            }
        }
    }

    impl ToolExecutor for MockToolExecutor {
        fn execute(&self, name: &str, args: &serde_json::Value, _session_id: Option<&str>) -> Result<String, String> {
            let mut results = self.results.lock().unwrap();
            let result = format!("ok: {}({})", name, args);
            results.push(result.clone());
            Ok(result)
        }
    }

    fn make_tool_call(name: &str, args: &str) -> ToolCall {
        ToolCall {
            typ: "function".to_string(),
            function: ToolCallFunction {
                index: None,
                name: name.to_string(),
                arguments: serde_json::from_str(args).unwrap_or(serde_json::Value::Null),
            },
        }
    }

    fn make_chat_response(
        message: Option<ChatMessage>,
        done: bool,
        finish_reason: Option<FinishReason>,
    ) -> ChatResponse {
        ChatResponse {
            message,
            done,
            finish_reason,
            eval_count: None,
            prompt_eval_count: None,
            usage: None,
        }
    }

    // --- Worker loop tests (no session store, no delegate) ---

    #[tokio::test]
    async fn worker_truncated_response_sets_flag() {
        let provider = MockProvider::new(vec![make_chat_response(
            Some(ChatMessage {
                role: "assistant".to_string(),
                content: "I was cut off".to_string(),
                tool_calls: None,
                tool_name: None,
            }),
            true,
            Some(FinishReason::Length),
        )]);
        let messages = vec![ChatMessage {
            role: "user".to_string(),
            content: "hello".to_string(),
            tool_calls: None,
            tool_name: None,
        }];
        let result = run_turn_with_messages_dyn(
            &provider as &dyn Provider,
            "test-model",
            messages,
            None,
            None,
            crate::config::DEFAULT_MAX_TOOL_LOOP_ITERATIONS,
            None,
        )
        .await
        .unwrap();
        assert!(result.truncated, "truncated flag should be true when finish_reason is Length");
    }

    #[tokio::test]
    async fn worker_normal_response_not_truncated() {
        let provider = MockProvider::new(vec![make_chat_response(
            Some(ChatMessage {
                role: "assistant".to_string(),
                content: "Hello!".to_string(),
                tool_calls: None,
                tool_name: None,
            }),
            true,
            Some(FinishReason::Stop),
        )]);
        let messages = vec![ChatMessage {
            role: "user".to_string(),
            content: "hello".to_string(),
            tool_calls: None,
            tool_name: None,
        }];
        let result = run_turn_with_messages_dyn(
            &provider as &dyn Provider,
            "test-model",
            messages,
            None,
            None,
            crate::config::DEFAULT_MAX_TOOL_LOOP_ITERATIONS,
            None,
        )
        .await
        .unwrap();
        assert!(!result.truncated, "truncated flag should be false for normal stop");
    }

    #[tokio::test]
    async fn worker_truncation_with_tool_calls_executes_and_injects_notice() {
        // Truncated response with a tool call: the loop should still execute
        // the tool call (it was fully emitted), inject a truncation notice,
        // and re-call the provider so any cut-off calls can be re-emitted.
        let provider = MockProvider::new(vec![
            make_chat_response(
                Some(ChatMessage {
                    role: "assistant".to_string(),
                    content: "I will write the file.".to_string(),
                    tool_calls: Some(vec![make_tool_call("write_file", r#"{"path":"test.txt"}"#)]),
                    tool_name: None,
                }),
                true,
                Some(FinishReason::Length),
            ),
            // Second call: normal stop after truncation notice
            make_chat_response(
                Some(ChatMessage {
                    role: "assistant".to_string(),
                    content: "That's all.".to_string(),
                    tool_calls: None,
                    tool_name: None,
                }),
                true,
                Some(FinishReason::Stop),
            ),
        ]);
        let executor = MockToolExecutor::new();
        let messages = vec![ChatMessage {
            role: "user".to_string(),
            content: "write a file".to_string(),
            tool_calls: None,
            tool_name: None,
        }];
        let result = run_turn_with_messages_dyn(
            &provider as &dyn Provider,
            "test-model",
            messages,
            None,
            Some(&executor as &dyn ToolExecutor),
            crate::config::DEFAULT_MAX_TOOL_LOOP_ITERATIONS,
            None,
        )
        .await
        .unwrap();

        assert!(result.truncated, "truncated flag should be true");
        // Tool call from truncated response SHOULD have been executed — it was fully emitted.
        let executed = executor.results.lock().unwrap();
        assert_eq!(
            executed.len(),
            1,
            "one tool call should execute from truncated response, got: {:?}",
            executed
        );
        assert!(executed[0].starts_with("ok: write_file"));
    }

    #[tokio::test]
    async fn worker_tool_calls_after_truncation_recovery() {
        // First: truncated text-only. Second: normal with tool call. Third: normal stop.
        let provider = MockProvider::new(vec![
            make_chat_response(
                Some(ChatMessage {
                    role: "assistant".to_string(),
                    content: "Let me think...".to_string(),
                    tool_calls: None,
                    tool_name: None,
                }),
                true,
                Some(FinishReason::Length),
            ),
            make_chat_response(
                Some(ChatMessage {
                    role: "assistant".to_string(),
                    content: "Now I'll read the file.".to_string(),
                    tool_calls: Some(vec![make_tool_call("read_file", r#"{"path":"test.txt"}"#)]),
                    tool_name: None,
                }),
                true,
                Some(FinishReason::Stop),
            ),
            make_chat_response(
                Some(ChatMessage {
                    role: "assistant".to_string(),
                    content: "Done!".to_string(),
                    tool_calls: None,
                    tool_name: None,
                }),
                true,
                Some(FinishReason::Stop),
            ),
        ]);
        let executor = MockToolExecutor::new();
        let messages = vec![ChatMessage {
            role: "user".to_string(),
            content: "read a file".to_string(),
            tool_calls: None,
            tool_name: None,
        }];
        let result = run_turn_with_messages_dyn(
            &provider as &dyn Provider,
            "test-model",
            messages,
            None,
            Some(&executor as &dyn ToolExecutor),
            crate::config::DEFAULT_MAX_TOOL_LOOP_ITERATIONS,
            None,
        )
        .await
        .unwrap();

        assert!(result.truncated);
        let executed = executor.results.lock().unwrap();
        assert_eq!(executed.len(), 1, "one tool call should execute after truncation recovery");
        assert!(executed[0].starts_with("ok: read_file"));
    }

    #[tokio::test]
    async fn worker_normal_tool_calls_execute() {
        let provider = MockProvider::new(vec![
            make_chat_response(
                Some(ChatMessage {
                    role: "assistant".to_string(),
                    content: "Reading file.".to_string(),
                    tool_calls: Some(vec![make_tool_call("read_file", r#"{"path":"a.txt"}"#)]),
                    tool_name: None,
                }),
                true,
                Some(FinishReason::Stop),
            ),
            make_chat_response(
                Some(ChatMessage {
                    role: "assistant".to_string(),
                    content: "Done!".to_string(),
                    tool_calls: None,
                    tool_name: None,
                }),
                true,
                Some(FinishReason::Stop),
            ),
        ]);
        let executor = MockToolExecutor::new();
        let messages = vec![ChatMessage {
            role: "user".to_string(),
            content: "read".to_string(),
            tool_calls: None,
            tool_name: None,
        }];
        let result = run_turn_with_messages_dyn(
            &provider as &dyn Provider,
            "test-model",
            messages,
            None,
            Some(&executor as &dyn ToolExecutor),
            crate::config::DEFAULT_MAX_TOOL_LOOP_ITERATIONS,
            None,
        )
        .await
        .unwrap();

        assert!(!result.truncated);
        let executed = executor.results.lock().unwrap();
        assert_eq!(executed.len(), 1);
        assert!(executed[0].starts_with("ok: read_file"));
    }

    #[tokio::test]
    async fn worker_truncation_injects_notice_message_into_history() {
        // Verify the truncation notice appears in messages sent to the second provider call.
        let second_call_messages: Arc<Mutex<Option<Vec<ChatMessage>>>> = Arc::new(Mutex::new(None));
        let captured = second_call_messages.clone();

        #[derive(Clone)]
        struct CapturingProvider {
            responses: Arc<Mutex<Vec<ChatResponse>>>,
            captured: Arc<Mutex<Option<Vec<ChatMessage>>>>,
        }

        #[async_trait]
        impl Provider for CapturingProvider {
            async fn chat(
                &self,
                _model: &str,
                messages: Vec<ChatMessage>,
                _stream: bool,
                _tools: Option<Vec<ToolDefinition>>,
            ) -> Result<ChatResponse, ProviderError> {
                let mut responses = self.responses.lock().unwrap();
                if responses.len() == 1 {
                    let mut captured = self.captured.lock().unwrap();
                    *captured = Some(messages);
                }
                if responses.is_empty() {
                    Ok(make_chat_response(
                        Some(ChatMessage {
                            role: "assistant".to_string(),
                            content: "no more".to_string(),
                            tool_calls: None,
                            tool_name: None,
                        }),
                        true,
                        None,
                    ))
                } else {
                    Ok(responses.remove(0))
                }
            }

            async fn chat_stream(
                &self,
                model: &str,
                messages: Vec<ChatMessage>,
                tools: Option<Vec<ToolDefinition>>,
                _on_chunk: &mut (dyn for<'a> FnMut(&'a str) + Send),
            ) -> Result<ChatResponse, ProviderError> {
                self.chat(model, messages, false, tools).await
            }
        }

        let provider = CapturingProvider {
            responses: Arc::new(Mutex::new(vec![
                make_chat_response(
                    Some(ChatMessage {
                        role: "assistant".to_string(),
                        content: "partial".to_string(),
                        tool_calls: None,
                        tool_name: None,
                    }),
                    true,
                    Some(FinishReason::Length),
                ),
                make_chat_response(
                    Some(ChatMessage {
                        role: "assistant".to_string(),
                        content: "recovered".to_string(),
                        tool_calls: None,
                        tool_name: None,
                    }),
                    true,
                    Some(FinishReason::Stop),
                ),
            ])),
            captured,
        };

        let messages = vec![ChatMessage {
            role: "user".to_string(),
            content: "hello".to_string(),
            tool_calls: None,
            tool_name: None,
        }];
        let result = run_turn_with_messages_dyn(
            &provider as &dyn Provider,
            "test-model",
            messages,
            None,
            None,
            crate::config::DEFAULT_MAX_TOOL_LOOP_ITERATIONS,
            None,
        )
        .await
        .unwrap();

        assert!(result.truncated);

        let captured_msgs = second_call_messages.lock().unwrap();
        let msgs = captured_msgs.as_ref().expect("should have captured messages from second call");
        // Messages: original user, assistant (truncated), user (notice)
        assert!(msgs.len() >= 3, "expected at least 3 messages, got {}", msgs.len());

        let notice_msgs: Vec<&ChatMessage> = msgs
            .iter()
            .filter(|m| m.role == "user" && m.content.contains("truncated"))
            .collect();
        assert_eq!(
            notice_msgs.len(),
            1,
            "should have exactly one truncation notice, got {:?}",
            notice_msgs
        );
        assert!(notice_msgs[0].content.contains("finish_reason: length"));
    }

    #[tokio::test]
    async fn worker_multiple_truncations_hit_max_loop() {
        let truncated_resp = make_chat_response(
            Some(ChatMessage {
                role: "assistant".to_string(),
                content: "still going...".to_string(),
                tool_calls: None,
                tool_name: None,
            }),
            true,
            Some(FinishReason::Length),
        );
        let provider = MockProvider::new(vec![
            truncated_resp.clone(),
            truncated_resp.clone(),
            truncated_resp.clone(),
            truncated_resp.clone(),
            truncated_resp.clone(),
            truncated_resp.clone(),
        ]);
        let messages = vec![ChatMessage {
            role: "user".to_string(),
            content: "keep going".to_string(),
            tool_calls: None,
            tool_name: None,
        }];
        // Use a small iteration limit to exercise the max-loop termination path.
        let result = run_turn_with_messages_dyn(
            &provider as &dyn Provider,
            "test-model",
            messages,
            None,
            None,
            3,
            None,
        )
        .await
        .unwrap();

        assert!(result.truncated, "should still report truncation");
        assert!(result.loop_limit_reached, "should hit loop limit with 3 iterations");
    }
}
